### PR TITLE
Fix: Fail to sanitize if the tag or attribute contains uppercase letters

### PR DESCRIPTION
**Pull request by ZhujiahuiFighting**
knownElements and knownAttributes are possible with uppercase. In function treeWalk, the tags and attributes passed in all call function ToLowerCase(). So if the element is linearGradient ( taking for an example ), it will be filtered out by JSanity, which is not expected.

### CODE REVIEW

**Comment by ZhujiahuiFighting** [comment]
@randomdross Hi David, could you please help review this CR? I have fixed one bug. Thanks in advance.

**Comment by randomdross** [comment]
It looks like the toLowerCase should stay because we want to normalize what we get out of the DOM itself.  I think what really needs to change is the individual entries in knownElements and knownAttributes that have some upper case letters.  Those should be changed to lower case.  It will be a bigger CR, but that seems like the better fix.

**Comment by scovetta** [comment]
I think the core of the issue is that the [SVG values](https://github.com/Microsoft/JSanity/blob/master/jsanity-0.3.js#L403) on the 'known' lists should all be lowercase to begin with. With the proposed change, the case would need to match exactly.

**Comment by ZhujiahuiFighting** [comment]
Make sense. Will update later. Thx.

**Comment by ZhujiahuiFighting** [comment]
Updated the CR.

**Comment by ZhujiahuiFighting** [comment]
Thanks for reminder @scovetta

**Comment by ZhujiahuiFighting** [comment]
Hi David, do you have more suggestions before the CR merges into master? @randomdross

**Comment by ZhujiahuiFighting** [comment]
Hi David, could you please take a look at this CR? Is it able to merge into master branch? Thanks in advance. @randomdross

**Pull request merged**
