### PR TITLE
Remove jquery

### PR DESCRIPTION
**Pull request by kh9n**
1. Remove all jQuery dependencies.
2. Remove Promise and async methods.
3. Only keep core feature for sanitize and remove others like insert result to document.

### CODE REVIEW

**Comment by randomdross** [comment]
This is fantastic, thank you!  At a high level though I do have an issue with making jSanity synchronous...  jSanity is async so that it can break up processing into small chunks and not block page rendering on the sanitize call.  This is a pretty important feature IMO, since otherwise sanitization can sit there completely blocking the UI thread for seconds (assuming a large chunk of input HTML to sanitize).  I would have liked to do everything in a web worker, but unfortunately web workers prohibit access to the DOM.

**Comment by randomdross** [comment]
...that being said, removing the dependency on jQuery is excellent!  And the global namespace is good too.

**Comment by kh9n** [comment]
@randomdross Thanks David! That is a great valid point about the performance concern. However, I think current async version has exactly same performance drop when a really huge HTML code need to be sanitize, that is the core logic (**treeWalk**) navigate inside of dom for purify is a recursive and synchronize method -- it will not return until all node from given HTML be processed.

to simulate the case for huge or complex HTML code, I force a sleep at entry of "treeWalk" for seconds, even for current async implementation, it will still hang the UI. You can find the demo here: [heavy sanitize demo](http://jsbin.com/qohosadeza/edit?html,js,console,output)

So, I think the better way to mitigate the perf concern on huge HTML is make the treeWalk to be a-synchronized.

**Comment by randomdross** [comment]
If you're seeing it hang like that it would be a bug.  I'm seeing the correct behavior (no blocking) on the benchmark page.  My process:
1)  Load the benchmark page: http://jsanity.azurewebsites.net/jsanity-benchmark-pretty.htm
(I'm using Chrome, though you should see the same result in FF or Edge.)
2)  Click the "Sanitize with jSanity" button.
3)  Observe "synchronous return" after 1ms, whereas all processing takes a second or so.

**Comment by randomdross** [comment]
If you just sleep for 1 second, anywhere (outside of a web worker), this will always hang the browser.  Async code can't help with that.  The only thing that would prevent that is if the code were truly multi-threaded and used a web worker.  Code that uses the DOM can't do that, unfortunately.  

The async approach enables cooperative multi-tasking, so code on the page has an opportunity to execute in between batches of sanitization workload.

Try this:
1) Load the benchmark page: http://jsanity.azurewebsites.net/jsanity-benchmark-pretty.htm
(I'm using Chrome, though you should see the same result in FF or Edge.)
2) Click the "Sanitize with jSanity" button.
3) Observe "synchronous return" after 1ms, whereas all processing takes a second or so.
I should probably add an animation or something on the benchmark page so it's easier to see how code on the page isn't blocked waiting on the entire sanitization workload to complete before it can execute.

**Comment by kh9n** [comment]
@randomdross I was trying to load a complex HTML page through ajax rather than use sleep, but it can't make $.ajax work on jsbin. :(

For the story of use async or sync, I think we still could keep the sanitize process as synchronize (as the core logic right now is synchronize), but let user make their best decision. 

Like, people still able to wrap the synchronize call into any promise implementation or just native setTimeout manner, then run those in the async way.
For people who don't have performance concern, they can choose the synchronize way, or add asynchronize wrapper base on their needs.

My point of view is, as support async run is not the core functionality of jSanity (at least, not the priority for now), by removing that restriction, we could give user some flexibility and enable more scenarios.

**Comment by randomdross** [comment]
If the API is synchronous, the best that a caller can do with a 5 second sanitization operation is to call the API and have it block for a full five seconds.  There's no opportunity during those 5 seconds for other script to run.
For many applications I would expect it to be a non-starter to have an API that blocks on the main thread like that.
I wouldn't be opposed to a flag to call the API synchronously, but I do think it does need to maintain its async ability.  Or otherwise find some magical way to use web workers.
It would be amazing to be able to get rid of jQuery though.  This becomes more feasible as older browsers go out of support and we can move to ES6 promises.

Date: Wed, 3 Feb 2016 22:49:55 -0800

**Comment by kh9n** [comment]
Hello david, 
I made some other changes, and it's some outline:
1. Open the door both for async or sync, it will auto switch depends on if any onFinishedCallback passed in.
2. Try to address the concern for the synchronized way of treeWalker for huge HTML, basically I wrap each node processing into a single job, and those jobs could be run continuously(sync), or in parallel(async).

for "huge" HTML (I use https://github.com/Microsoft/JSanity/blob/master/jsanity-0.2.js as test case):
in sync mode: it takes around 280 ms
in async mode: it takes around 30 seconds
in optimized async mode: it takes around 330 ms

Add the jsfiddle link for the [demo](https://jsfiddle.net/69emxvkk/1/)

**Comment by randomdross** [comment]
Oh wow, that looks fantastic!  Give me a few days to play around with this a bit before I make the decision to pull it in, it's a big change.
Are you saying that async was originally 30 seconds but then you optimized and got it down to 330ms?  (Or are there actually two different async modes?)
Date: Fri, 5 Feb 2016 04:35:41 -0800

**Comment by kh9n** [comment]
For sure, that does a big change and take your time.

And yes, it's not typo, truly 30 seconds. Reason the not optimized solution takes so long is because if there're many nodes, and process a single node is so fast(<1ms), time spend on waiting for the next job (>15 ms) is very very expensive.

So the optimize is that i will pick at least one job and run them in synchronize way until the total execution time longer than 15ms.

**Comment by randomdross** [comment]
Sorry for the delay!  Having spent some time with the new code, I'm now even more excited about it!  Take a look at this feedback and make any changes, then I'll merge your version into the original.

Ok, here's a version of my original benchmark page that's updated to use your implementation:
http://jsanity.azurewebsites.net/jsanity-benchmark-pretty-test.htm

For comparison, here's the benchmark page for the original implementation:
http://jsanity.azurewebsites.net/jsanity-benchmark-pretty.htm

Just to be consistent, both my benchmark pages insert the sanitized nodes into the DOM.

Notes:
- On my machine, the original jSanity returns synchronously immediately (3ms).  In async mode, the new code takes a little longer (~150ms).  This isn't a big deal, but I wonder why it isn't returning more immediately.
- The original jSanity finishes all its work in ~950ms on average.
- The new jSanity finishes in ~1000ms on average.  However it seems that the new implementation yields quite a bit more so other activities on the page will have more of a chance to operate.  Here's what I see:
  Original run:   XXXXXXXXXXXXXX.XXX.XXX.#
  Your new code:  XXXX.XX..............XX.............XX..#
- The new version (synchronous) finishes in ~850ms.
  New code, sync: XXXXXXXXXXXXXXXXX..#

Other notes:
- I noticed that you're missing the support for maxWidth / maxHeight / overflow enforcement.  Can you put it back?  =)  This is a security feature.
  - The code is at line 870 in https://github.com/Microsoft/JSanity/blob/master/jsanity-0.2.js
- I like that you just return a node that can be appended as necessary.  That makes more sense than the way I was doing it.
- I seem to have only half-removed the support for toStaticHTML from my code.  It looks like you re-implemented the part I removed.  Thanks!  =)  We can probably remove the old IE compat code at this point since IE < 11 is now unsupported.

**Comment by randomdross** [comment]
Also let me know if you're @kh9n on Twitter, I'd like to credit you when I tweet about the change.

**Comment by kh9n** [comment]
Hello @randomdross, I just back from vacation and modified according to your feedback. I really appreciate you like the changes.
Regarding to your question why the new implementation will not return immediately, the reason is that:
1. The original implementation will schedule run for top node, and then return.
2. The new code will schedule will schedule runs for top nodes, **and process them before return**.

And yes, my twitter account is **kh9n** as well.

**Comment by kh9n** [comment]
And BTW:// I am not sure if I do the right thing about max-width/max-height/overflow, as the original code it will be added to the parent of purified node; but as in the new code there's no parent, so I just add it to the root of purified nodes.

**Comment by randomdross** [comment]
I submitted a pull request to set "display: inline-block" so that max-width/max-heigh works even when the parent of the purified node is a span.  "display:block" would also work, but "display: inline-block" seems to be a better option, I think.  Let me know if you see any issue with this.  I'll go ahead and merge your branch now and fix up the benchmark / test pages to work with it.

**Comment by randomdross** [comment]
Aha, I found one more bug.  The code to call link click callbacks (the 'linkClickCallback' sanitization option) was mixed in with some of the jQuery promise stuff and was removed.  I will continue with the pull request here but it would be great if you can bring back support for this.

To test, try the last test in jsanity-demo-pretty.htm.  Sanitize and click "link to Microsoft."  With the old code, the specified linkClickCallback would be called, but not with the new code.

**Comment by randomdross** [comment]
Ok, I merged the pull request and then also I merged the change to use inline-block:
output.style.setProperty("display", "inline-block");

I didn't attempt to fix the linkClickCallback support though.

**Comment by randomdross** [comment]
Also, I've added you as a collaborator on Microsoft/JSanity.  =)

**Comment by kh9n** [comment]
@randomdross I've fix the linkClickCallback issue and make another pull request, with another fix that check the execution environment for jSanity before run.

And thank you that is my honor to be a contributor and able continue to contribute to this great project!

**Comment by randomdross** [comment]
Excellent, I confirm linkClickCallback works now, thank you!  The next thing on my radar is to fix the identified DOM clobbering issues.  Hopefully I'll get some time in the next few weeks to work through that.

**Pull request merged**
